---
groups:
    allvms:
        vmNameSearchTemplate: '\S*'
        active: false
        order : 2
    ldapservers:
        vmNameBuildTemplate: 'ldapsrv'
        active: True
        vmCount: 2
        networkBaseAddress: 200
        order : 0
        addsetting: True
        setingvar: "ldap_servers"
        ownvar: "addreses"
    ldapmasters:
        vmNameSearchTemplate: 'ldapsrv1'
        active: False
        order : 2
    ldapslaves:    
        vmNameSearchTemplate: 'ldapsrv[2..9]+'
        active: False
        order : 2
    ldapclients:
        vmNameBuildTemplate: 'workstation'
        active: True
        vmCount: 1
        networkBaseAddress: 100
        order : 1

settings:
    ldap_service: "slapd"
    ldap_port: "339"
    dn_repluser: "repluser"
    dn_repluserFullName: "User for ldap replication"
    SSHAreplPWD: "{SSHA}nR+wYuff6LRH2zkn54wvcz0b2VsyOkuC"   #UniQue#Passw0rd
    CLRrootPWD: "ldp#passw0rd"
    SSHARootPWD: "{SSHA}7P/9Hf7ckkGn87/jaje9CqcCcjRn65wP"   #ldp#passw0rd
    dn_admin: "cn=ldapadm,dc=infi-test,dc=local"
    dn_dc: "infi-test"
    dn_firstOU: "FirstOU"
    dn_firstGroup: "Bifurcation"
    dn_user: "flyx"
    dn_userFullName: "Huge unpredictible Fluctuation"
    SSHAuserPWD: "{SSHA}xqAQU/brcjDTr0NuTUS9MhDNEWRa9llI" #Unique#Passw0rd
    dn_Suffix: "dc=infi-test,dc=local"
    network: "192.168.33."
    dn_replretry: "30 5 300 3"
    dn_replinterval: "00:00:05:00"
#    ldap_master: "192.168.33.254"
#    ldap_slave: "192.168.33.253"
