---
- name: restart ldap
  become: yes
  service:
    name: "{{ ldap_service }}"
    state: restarted
    enabled: yes

- name: restart firewalld
  become: yes
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: clear temporary files
  become: yes
  command: rm -f ~/*.ldif
  ignore_errors: True
