---
- name: restart ldap
  become: yes
  #service: name={{ ldap_service }} state=started enabled=yes
  service:
    name: "{{ ldap_service }}"
    state: restarted

- name: restart firewalld
  become: yes
  #service: name=firewalld state=started enabled=yes
  service:
    name: firewalld
    state: restarted

- name: restart rsyslog
  become: yes
  #service: name=firewalld state=started enabled=yes
  service:
    name: rsyslog
    state: restarted

- name: clear temporary files
  become: yes
  command: rm -f ~/*.ldif
  ignore_errors: True
