#TODO 20180429
#   1. Crate SELinux policy
#   2. Deploy configuration file
#   3. Join to domain

- name: LDAP packages are installed
  yum:
    name: '{{ item }}'
    state: present
    #yum: name={{ item }} state=installed
  with_items:
    - openldap
    - compat-openldap
    - openldap-clients
    - openldap-devel
    - openssh-ldap
    - python-ldap
    - openssl
    - libsemanage-python
    - nss-pam-ldapd

- name: add the client machine to LDAP 
  become: yes
  command: /usr/bin/authconfig --enableldap --enableldapauth --ldapserver={{ ldap_master }},{{ ldap_slave }} --ldapbasedn="{{ dn_Suffix }}" --enablemkhomedir --update
  notify:
    - restart ldap

