---
- name: add cosine LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
  notify:
    - restart ldap
  ignore_errors: True

- name: add nis LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
  notify:
    - restart ldap
  ignore_errors: True

- name: add cosine LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif
  notify:
    - restart ldap
  ignore_errors: True

- name: copy template ldap structure file
  become: yes
  template: src=base.tmpl dest=~/base.ldif
  notify:
    - clear temporary files

- name: modify ldap with structure file
  become: yes
  command: //usr/bin/ldapadd -x -w "{{ CLRrootPWD }}" -D "{{ dn_admin}}" ~/base.ldif
  ignore_errors: True
  notify:
    - restart ldap

- name: copy template ldap structure file
  become: yes
  template: src=syncprov.tmpl dest=~/syncprov.ldif
  notify:
    - clear temporary files

- name: modify ldap with replication sync file
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f ~/syncprov.ldif
  ignore_errors: True
  notify:
    - restart ldap

- name: copy template ldap replication user file
  become: yes
  template: src=repluser.tmpl dest=~/repluser.ldif
  notify:
    - clear temporary files

- name: modify ldap with replication user file
  become: yes
  command: /usr/bin/ldapadd -x -w "{{ CLRrootPWD }}" -D "{{ dn_admin}}" -f ~/repluser.ldif
  ignore_errors: True

- name: copy template ldap ordinal user file
  become: yes
  template: src=user.tmpl dest=~/user.ldif
  notify:
    - clear temporary files

- name: modify ldap with ordinal user file
  become: yes
  command: /usr/bin/ldapadd -x -w "{{ CLRrootPWD }}" -D "{{ dn_admin}}" -f ~/user.ldif
  ignore_errors: True
