---
- name: restart ldap
  become: yes
  #service: name={{ ldap_service }} state=started enabled=yes
  service:
    name: slapd
    state: restarted
    enabled: yes

- name: restart firewalld
  become: yes
  #service: name=firewalld state=started enabled=yes
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart rsyslog
  become: yes
  #service: name=firewalld state=started enabled=yes
  service:
    name: rsyslog
    state: restarted
    enabled: yes

