---
#TODO 20180501
#   1. Change "Configure SELinux to start openldap" to real policy

- name: LDAP packages are installed
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openldap
    - compat-openldap
    - openldap-clients
    - openldap-servers
    - openldap-servers-sql
    - openldap-devel
    - openssh-ldap
    - python-ldap
    - openssl
    - libsemanage-python
    - cyrus-sasl
    - cyrus-sasl-devel
    - libtool-ltdl
    - unixODBC
  notify:
    - restart ldap

- name: Configure SELinux to start openldap on any port
  become: yes
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: start firewalld
  become: yes
  ignore_errors: yes
  service:
    name: firewalld
    state: started
    enabled: yes

- name: insert firewalld rule for ldap port 389
  become: yes
  firewalld: port=389/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  notify:
    - restart firewalld

- name: insert firewalld rule for ldap port 636
  become: yes
  firewalld: port=636/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  notify:
    - restart firewalld

- name: insert firewalld rule for ldap port 9830
  become: yes
  firewalld: port=9830/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  notify:
    - restart firewalld

- name: start ldap
  become: yes
  service:
    name: slapd
    state: started
    enabled: yes

- name: Configure Rsyslog to log LDAP
  become: yes
  command: echo "local4.* /var/log/ldap.log" >> /etc/rsyslog.conf
  notify:
    - restart rsyslog

- name: copy template ldap configuration file
  become: yes
  template: src=db.tmpl dest=~/db.ldif
  notify:
    - clear temporary files

- name: modify ldap with configuration file
  become: yes
  command: /usr/bin/ldapmodify -Y EXTERNAL -H ldapi:/// -f ~/db.ldif
  notify:
    - restart ldap

- name: copy database configuration file
  become: yes
  template: src=DB_CONFIG.tmpl dest=/var/lib/ldap/DB_CONFIG
  notify:
    - restart ldap

- name: add cosine LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
  notify:
    - restart ldap
  ignore_errors: True

- name: add nis LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
  notify:
    - restart ldap
  ignore_errors: True

- name: add inetorgperson LDAP schema
  become: yes
  command: /usr/bin/ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif
  notify:
    - restart ldap
  ignore_errors: True


