- name: LDAP packages are installed
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openldap
    - compat-openldap
    - openldap-clients
    - openldap-servers
    - openldap-servers-sql
    - openldap-devel
    - openssh-ldap
    - python-ldap
    - openssl

- name: Configure SELinux to start openldap on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for ldap
  firewalld: port={{ ldap_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Start openldap Service
  service: name={{ ldap_service }} state=started enabled=yes


#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes

    #yum: name={{ item }} state=installed
    #remote_user: vagrant
    #
    #become_method: su

