#TODO 20180429
#   1. Change "Configure SELinux to start openldap" to real policy
#   2. Deploy configuration file
#   3. Deploy replication

- name: LDAP packages are installed
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openldap
    - compat-openldap
    - openldap-clients
    - openldap-servers
    - openldap-servers-sql
    - openldap-devel
    - openssh-ldap
    - python-ldap
    - openssl
    - libsemanage-python
    - cyrus-sasl
    - cyrus-sasl-devel
    - libtool-ltdl
    - unixODBC
  notify:
    - restart ldap

- name: Configure SELinux to start openldap on any port
  become: yes
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: start firewalld
  become: yes
  ignore_errors: yes
  service:
    name: firewalld
    state: started

- name: insert firewalld rule for ldap
  become: yes
  firewalld: port={{ ldap_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  notify:
    - restart firewalld

- name: start ldap
  become: yes
  #service: name={{ ldap_service }} state=started enabled=yes
  service:
    name: "{{ ldap_service }}"
    state: started

- name: Configure Rsyslog to log LDAP
  become: yes
  command: echo "local4.* /var/log/ldap.log" >> /etc/rsyslog.conf
  notify:
    - restart rsyslog

