---
# This playbook deploys the whole application stack in this site.

- name: settings for all vm 
  hosts: allvms
  roles:
    - common


- name: install ldap ldapsmaster server
  hosts: ldapmasters
  roles:
    - ldapserver
    - ldapmaster

- name: install ldap slave server
  hosts: ldapslaves
  roles:
    - ldapserver
    - ldapslave

- name: install ldap client
  hosts: ldapclients
  roles:
    - ldapclient
