---
- name: copy ldap replication configuration file
  become: yes
  template: src=repl.tmpl dest=~/repl.ldif
  notify:
    - clear temporary files
    
- name: modify ldap with configuration file
  become: yes
  command: /usr/bin/ldapmodify -Y EXTERNAL -H ldapi:/// -f ~/repl.ldif
  ignore_errors: True
  notify:
    - restart ldap
